test_that("customise_table() works on gt table", {
  gt_obj <- summary_table(mtcars, by = am) |>
    add_summary(vars = c(mpg, wt)) |>
    tbl_stats()

  styled <- customise_table(gt_obj)

  expect_s3_class(styled, "gt_tbl")
})

test_that("customise_table() updates title and subtitle", {
  gt_obj <- summary_table(mtcars, by = am) |>
    add_summary(vars = c(mpg, wt)) |>
    tbl_stats()

  styled <- customise_table(
    gt_obj,
    title = "My title",
    subtitle = "My subtitle"
  )

  expect_s3_class(styled, "gt_tbl")
})

test_that("customise_table() relabels columns", {
  gt_obj <- summary_table(mtcars, by = am, overall = TRUE) |>
    add_summary(vars = c(mpg, wt)) |>
    tbl_stats()

  styled <- customise_table(
    gt_obj,
    col_labels = c("Level" = "", "am = 1" = "Manual", "am = 0" = "Automatic")
  )

  expect_s3_class(styled, "gt_tbl")
})

test_that("customise_table() relabels row and level values for Variable tables", {
  gt_obj <- summary_table(mtcars, by = am) |>
    add_summary(vars = c(mpg, cyl)) |>
    tbl_stats()

  styled <- customise_table(
    gt_obj,
    row_labels = c("mpg" = "Miles per gallon", "cyl" = "Cylinders"),
    level_labels = c("4" = "4 cylinders", "6" = "6 cylinders", "8" = "8 cylinders")
  )

  expect_s3_class(styled, "gt_tbl")
})

test_that("customise_table() relabels row values for Measure tables", {
  gt_obj <- crosstabs(mtcars, row = am, col = vs) |>
    tbl_stats()

  styled <- customise_table(
    gt_obj,
    row_labels = c(
      "Risk ratio" = "RR",
      "Odds ratio" = "OR"
    )
  )

  expect_s3_class(styled, "gt_tbl")
})

test_that("customise_table() preserves footnotes from tbl_stats output", {
  gt_obj <- summary_table(mtcars, by = am) |>
    add_summary(vars = c(mpg, wt)) |>
    add_p() |>
    tbl_stats()

  styled <- customise_table(
    gt_obj,
    theme = "journal",
    accent_color = "#123B7A"
  )

  expect_s3_class(styled, "gt_tbl")
})

test_that("customise_table() supports journal theme", {
  gt_obj <- summary_table(mtcars, by = am) |>
    add_summary(vars = c(mpg, wt)) |>
    tbl_stats()

  styled <- customise_table(gt_obj, theme = "journal")

  expect_s3_class(styled, "gt_tbl")
})

test_that("customise_table() supports classic theme", {
  gt_obj <- summary_table(mtcars, by = am) |>
    add_summary(vars = c(mpg, wt)) |>
    tbl_stats()

  styled <- customise_table(gt_obj, theme = "classic")

  expect_s3_class(styled, "gt_tbl")
})

test_that("customise_table() supports minimal theme", {
  gt_obj <- summary_table(mtcars, by = am) |>
    add_summary(vars = c(mpg, wt)) |>
    tbl_stats()

  styled <- customise_table(gt_obj, theme = "minimal")

  expect_s3_class(styled, "gt_tbl")
})

test_that("customise_table() supports compact theme", {
  gt_obj <- summary_table(mtcars, by = am) |>
    add_summary(vars = c(mpg, wt)) |>
    tbl_stats()

  styled <- customise_table(gt_obj, theme = "compact")

  expect_s3_class(styled, "gt_tbl")
})

test_that("customise_table() supports default theme explicitly", {
  gt_obj <- summary_table(mtcars, by = am) |>
    add_summary(vars = c(mpg, wt)) |>
    tbl_stats()

  styled <- customise_table(gt_obj, theme = "default")

  expect_s3_class(styled, "gt_tbl")
})

test_that("customise_table() supports alignment options including center", {
  gt_obj <- summary_table(mtcars, by = am, overall = TRUE) |>
    add_summary(vars = c(mpg, wt)) |>
    tbl_stats()

  styled <- customise_table(
    gt_obj,
    align = list(
      left = c("Variable", "Level"),
      right = c("am = 1", "am = 0"),
      center = c("Overall")
    )
  )

  expect_s3_class(styled, "gt_tbl")
})

test_that("customise_table() supports hide_cols", {
  gt_obj <- summary_table(mtcars, by = am) |>
    add_summary(vars = c(mpg, wt)) |>
    tbl_stats()

  styled <- customise_table(
    gt_obj,
    hide_cols = "Level"
  )

  expect_s3_class(styled, "gt_tbl")
})

test_that("customise_table() supports source note", {
  gt_obj <- summary_table(mtcars, by = am) |>
    add_summary(vars = c(mpg, wt)) |>
    tbl_stats()

  styled <- customise_table(
    gt_obj,
    source_note = "Generated by GTstats"
  )

  expect_s3_class(styled, "gt_tbl")
})

test_that("customise_table() supports bold and italic column styling", {
  gt_obj <- summary_table(mtcars, by = am, overall = TRUE) |>
    add_summary(vars = c(mpg, wt)) |>
    tbl_stats()

  styled <- customise_table(
    gt_obj,
    bold_cols = c("Variable"),
    italic_cols = c("Overall")
  )

  expect_s3_class(styled, "gt_tbl")
})

test_that("customise_table() supports font size override", {
  gt_obj <- summary_table(mtcars, by = am) |>
    add_summary(vars = c(mpg, wt)) |>
    tbl_stats()

  styled <- customise_table(
    gt_obj,
    font_size = 11
  )

  expect_s3_class(styled, "gt_tbl")
})

test_that("customise_table() supports row striping on", {
  gt_obj <- summary_table(mtcars, by = am) |>
    add_summary(vars = c(mpg, wt)) |>
    tbl_stats()

  styled <- customise_table(
    gt_obj,
    row_striping = TRUE
  )

  expect_s3_class(styled, "gt_tbl")
})

test_that("customise_table() supports row striping off", {
  gt_obj <- summary_table(mtcars, by = am) |>
    add_summary(vars = c(mpg, wt)) |>
    tbl_stats()

  styled <- customise_table(
    gt_obj,
    row_striping = FALSE
  )

  expect_s3_class(styled, "gt_tbl")
})

test_that("customise_table() supports accent color and stripe color", {
  gt_obj <- summary_table(mtcars, by = am) |>
    add_summary(vars = c(mpg, wt)) |>
    tbl_stats()

  styled <- customise_table(
    gt_obj,
    accent_color = "#123B7A",
    stripe_color = "#F5F5F5"
  )

  expect_s3_class(styled, "gt_tbl")
})

test_that("customise_table() renders an unrendered gtstats result", {
  obj <- summary_table(mtcars, by = am) |>
    add_summary(vars = c(mpg, wt))

  expect_s3_class(customise_table(obj), "gt_tbl")
})
